name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.25-trixie
    steps:
      - run: apt update && apt install -y libgtk-4-dev libgtk4-layer-shell-dev git cosign gobject-introspection
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26
        with:
          subject-checksums: ./dist/checksums.txt
